### ISSUE TITLE
Thesis presentation slides

### ISSUE THREAD

**Issue by HediDelpazir** [mpoeter/emr#1]
Hi Manuel,

Is it possible to send your thesis presentation slides too. I interested to see that.

Best.

**Comment by mpoeter** [comment]
Hi Hedi, what exactly are you interested in?

**Comment by HediDelpazir** [comment]
> Hi Hedi, what exactly are you interested in?

As my thesis subject is memory reclamation too, i interested to see your presentation. I currently work on stamp-it and have some idea based on two recent proposed scheme to make it more efficient

**Comment by mpoeter** [comment]
You can contact me directly at manuel[at]manuel-poeter[dot]at - I am happy to share various presentations and discuss the topic in general. And I am particularly interested in your new ideas! :slightly_smiling_face:

**Comment by HediDelpazir** [comment]
> You can contact me directly at manuel[at]manuel-poeter[dot]at - I am happy to share various presentations and discuss the topic in general. And I am particularly interested in your new ideas! slightly_smiling_face

Surely, i will be happy too.
